/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    service_users: ServiceUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    soc_generic: SocGeneric;
    soc_alert: SocAlert;
    customers: Customer;
    soc_visitors: SocVisitor;
    bcix_alert: BcixAlert;
    visitors: Visitor;
    service_users: ServiceUser;
    external_alerts: ExternalAlert;
    auto_reports: AutoReport;
    post_entries: PostEntry;
    meeting_protocols: MeetingProtocol;
    management_protocols: ManagementProtocol;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    soc_generic: SocGenericSelect<false> | SocGenericSelect<true>;
    soc_alert: SocAlertSelect<false> | SocAlertSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    soc_visitors: SocVisitorsSelect<false> | SocVisitorsSelect<true>;
    bcix_alert: BcixAlertSelect<false> | BcixAlertSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    service_users: ServiceUsersSelect<false> | ServiceUsersSelect<true>;
    external_alerts: ExternalAlertsSelect<false> | ExternalAlertsSelect<true>;
    auto_reports: AutoReportsSelect<false> | AutoReportsSelect<true>;
    post_entries: PostEntriesSelect<false> | PostEntriesSelect<true>;
    meeting_protocols: MeetingProtocolsSelect<false> | MeetingProtocolsSelect<true>;
    management_protocols: ManagementProtocolsSelect<false> | ManagementProtocolsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'de';
  user:
    | (User & {
        collection: 'users';
      })
    | (ServiceUser & {
        collection: 'service_users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ServiceUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'user_general' | 'user_soc' | 'manager_soc' | 'manager_general';
  username: string;
  first_name: string;
  last_name: string;
  phone?: string | null;
  avatar?: (string | null) | Media;
  department:
    | 'Geschäftsführung'
    | 'Netzwerk'
    | 'Server'
    | 'Entwicklung'
    | 'SOC'
    | 'Vertrieb'
    | 'Buchhaltung'
    | 'Controling'
    | 'Generic';
  _status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soc_generic".
 */
export interface SocGeneric {
  id: string;
  user?: (string | null) | User;
  lead: string | User;
  employees: string;
  date: string;
  shift: '0' | '1' | '2';
  events: string;
  special_events?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soc_alert".
 */
export interface SocAlert {
  id: string;
  user?: (string | null) | User;
  employee: string | User;
  date: string;
  time: string;
  customer: string | Customer;
  events: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  contact?:
    | {
        name?: string | null;
        phone?: string | null;
        email?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  _status: 'active' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soc_visitors".
 */
export interface SocVisitor {
  id: string;
  user?: (string | null) | User;
  employee: string | User;
  date: string;
  start: string;
  end: string;
  reason: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bcix_alert".
 */
export interface BcixAlert {
  id: string;
  user?: (string | null) | User;
  eventType: 'ALERT' | 'ACCEPT' | 'RESOLVE';
  priority: 'LOW' | 'HIGH';
  alertKey: string;
  summary: string;
  details: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: string;
  employee: string | User;
  name: string;
  cardId: string;
  daysOfVisit: {
    date: string;
    start: string;
    end: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_users".
 */
export interface ServiceUser {
  id: string;
  name: string;
  role: 'service_account';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external_alerts".
 */
export interface ExternalAlert {
  id: string;
  customer: string | Customer;
  reference_id: string;
  asset: {
    host: string;
    alias?: string | null;
  };
  level: 'MEDIUM' | 'HIGH' | 'CRITICAL' | 'HIGH CRITICAL';
  description?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auto_reports".
 */
export interface AutoReport {
  id: string;
  user_lvl1?: (string | null) | User;
  user_lvl2?: (string | null) | User;
  customer: string | Customer;
  alarms: {
    external_alarm: string | ExternalAlert;
    id?: string | null;
  }[];
  soc_l1: {
    relevance: boolean;
    notes?: string | null;
    finished: string;
  };
  soc_l2?: {
    valid_incident?: boolean | null;
    notes?: string | null;
    level?: ('LOW' | 'MEDIUM' | 'HIGH') | null;
    finished?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post_entries".
 */
export interface PostEntry {
  id: string;
  user?: (string | null) | User;
  serial_number: string;
  date_of_record: string;
  date_of_letter: string;
  recipient: string;
  subject: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meeting_protocols".
 */
export interface MeetingProtocol {
  id: string;
  user?: (string | null) | User;
  organizer: string | User;
  date: string;
  location: 'Geschäftsführungraum' | 'Besprechungsraum' | 'Verwaltungsbüro' | 'Teams' | 'Arbeitsplatz';
  start_time: string;
  end_time: string;
  participants_intern: string;
  participants_extern?: string | null;
  topic: 'weekly' | 'verwaltung';
  tasks: {
    topic: string;
    content: string;
    accountable?: string | null;
    due_date?: string | null;
    status: 'to_do' | 'done' | 'postponed';
    id?: string | null;
  }[];
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management_protocols".
 */
export interface ManagementProtocol {
  id: string;
  user?: (string | null) | User;
  organizer: string | User;
  date: string;
  location: 'Geschäftsführungraum' | 'Besprechungsraum' | 'Verwaltungsbüro' | 'Teams' | 'Arbeitsplatz';
  start_time: string;
  end_time: string;
  participants_intern: string;
  participants_extern?: string | null;
  topic: 'weekly' | 'verwaltung';
  tasks: {
    topic: string;
    content: string;
    accountable?: string | null;
    due_date?: string | null;
    status: 'to_do' | 'done' | 'postponed';
    id?: string | null;
  }[];
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'soc_generic';
        value: string | SocGeneric;
      } | null)
    | ({
        relationTo: 'soc_alert';
        value: string | SocAlert;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'soc_visitors';
        value: string | SocVisitor;
      } | null)
    | ({
        relationTo: 'bcix_alert';
        value: string | BcixAlert;
      } | null)
    | ({
        relationTo: 'visitors';
        value: string | Visitor;
      } | null)
    | ({
        relationTo: 'service_users';
        value: string | ServiceUser;
      } | null)
    | ({
        relationTo: 'external_alerts';
        value: string | ExternalAlert;
      } | null)
    | ({
        relationTo: 'auto_reports';
        value: string | AutoReport;
      } | null)
    | ({
        relationTo: 'post_entries';
        value: string | PostEntry;
      } | null)
    | ({
        relationTo: 'meeting_protocols';
        value: string | MeetingProtocol;
      } | null)
    | ({
        relationTo: 'management_protocols';
        value: string | ManagementProtocol;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'service_users';
        value: string | ServiceUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'service_users';
        value: string | ServiceUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  username?: T;
  first_name?: T;
  last_name?: T;
  phone?: T;
  avatar?: T;
  department?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soc_generic_select".
 */
export interface SocGenericSelect<T extends boolean = true> {
  user?: T;
  lead?: T;
  employees?: T;
  date?: T;
  shift?: T;
  events?: T;
  special_events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soc_alert_select".
 */
export interface SocAlertSelect<T extends boolean = true> {
  user?: T;
  employee?: T;
  date?: T;
  time?: T;
  customer?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  contact?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        role?: T;
        id?: T;
      };
  notes?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soc_visitors_select".
 */
export interface SocVisitorsSelect<T extends boolean = true> {
  user?: T;
  employee?: T;
  date?: T;
  start?: T;
  end?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bcix_alert_select".
 */
export interface BcixAlertSelect<T extends boolean = true> {
  user?: T;
  eventType?: T;
  priority?: T;
  alertKey?: T;
  summary?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  employee?: T;
  name?: T;
  cardId?: T;
  daysOfVisit?:
    | T
    | {
        date?: T;
        start?: T;
        end?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_users_select".
 */
export interface ServiceUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external_alerts_select".
 */
export interface ExternalAlertsSelect<T extends boolean = true> {
  customer?: T;
  reference_id?: T;
  asset?:
    | T
    | {
        host?: T;
        alias?: T;
      };
  level?: T;
  description?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auto_reports_select".
 */
export interface AutoReportsSelect<T extends boolean = true> {
  user_lvl1?: T;
  user_lvl2?: T;
  customer?: T;
  alarms?:
    | T
    | {
        external_alarm?: T;
        id?: T;
      };
  soc_l1?:
    | T
    | {
        relevance?: T;
        notes?: T;
        finished?: T;
      };
  soc_l2?:
    | T
    | {
        valid_incident?: T;
        notes?: T;
        level?: T;
        finished?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post_entries_select".
 */
export interface PostEntriesSelect<T extends boolean = true> {
  user?: T;
  serial_number?: T;
  date_of_record?: T;
  date_of_letter?: T;
  recipient?: T;
  subject?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meeting_protocols_select".
 */
export interface MeetingProtocolsSelect<T extends boolean = true> {
  user?: T;
  organizer?: T;
  date?: T;
  location?: T;
  start_time?: T;
  end_time?: T;
  participants_intern?: T;
  participants_extern?: T;
  topic?: T;
  tasks?:
    | T
    | {
        topic?: T;
        content?: T;
        accountable?: T;
        due_date?: T;
        status?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management_protocols_select".
 */
export interface ManagementProtocolsSelect<T extends boolean = true> {
  user?: T;
  organizer?: T;
  date?: T;
  location?: T;
  start_time?: T;
  end_time?: T;
  participants_intern?: T;
  participants_extern?: T;
  topic?: T;
  tasks?:
    | T
    | {
        topic?: T;
        content?: T;
        accountable?: T;
        due_date?: T;
        status?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}