import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";
import AlertDialogDemo from "@/components/AlertNewAlarm";
// import { Inter } from "next/font/google";
import AlertCheckUser from "@/components/AlertNewAlarm";

const Inter = localFont({
  src: [
    {
      path: "../../fonts/static/Inter_24pt-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/static/Inter_24pt-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../fonts/static/Inter_24pt-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../fonts/static/Inter_24pt-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reportus 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" className="h-full">
      <body
        className={cn("relative h-full font-sans antialiased", Inter.className)}
      >
        <main className="relative flex flex-col min-h-screen">
          <Providers>
            <Navbar></Navbar>
            <div className="flex-grow flex-1">{children}</div>

            <AlertCheckUser />

            <Footer></Footer>
          </Providers>
        </main>

        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
