export const MITRE = [
  ["HIGH CRITICAL", "HIGH CRITICAL", "CRITICAL"],
  ["HIGH CRITICAL", "CRITICAL", "MEDIUM"],
  ["CRITICAL", "CRITICAL", "MEDIUM"],
  ["MEDIUM", "MEDIUM", "LOW"],
] as const;

export const VULNERABILITIES = [
  ["HIGH CRITICAL", "HIGH CRITICAL", "CRITICAL"],
  ["HIGH CRITICAL", "HIGH CRITICAL", "CRITICAL"],
  ["HIGH CRITICAL", "CRITICAL", "CRITICAL"],
  ["CRITICAL", "CRITICAL", "MEDIUM"],
] as const;

export const ALERT_MATRICE = [
  ["LOW", "LOW", "MEDIUM", "MEDIUM"],
  ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
  ["CRITICAL", "CRITICAL", "CRITICAL", "HIGH CRITICAL"],
] as const;
